# Generated by Django 4.0 on 2024-01-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_disposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('author_all', models.TextField()),
                ('pub_year', models.IntegerField()),
                ('publisher', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=200)),
                ('owned_at', models.DateTimeField(auto_now_add=True)),
                ('disposed_at', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book_owned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('author_key', models.CharField(max_length=200)),
                ('author_all', models.TextField()),
                ('pub_year', models.IntegerField()),
                ('publisher', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=200)),
                ('owned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.TextField()),
                ('memo', models.TextField()),
            ],
        ),
    ]
